# Generated by Django 3.1.4 on 2021-01-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210119_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date', '-updated', 'timestamp']},
        ),
    ]
